config/routes.rb
Rails.application.routes.draw do
  resources :apimaps
  get 'home/index'
  root 'home#index'
  get 'home/map'
  get 'home/test'
  get 'home/heatmap'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apimap.rb
class Apimap < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apimaps_controller.rb
class ApimapsController < ApplicationController
  before_action :set_apimap, only: [:show, :edit, :update, :destroy]

  # GET /apimaps
  # GET /apimaps.json
  def index
    @apimaps = Apimap.all
    @hash = Gmaps4rails.build_markers(@apimaps) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
      marker.infowindow map.name
    end
  end

  # GET /apimaps/1
  # GET /apimaps/1.json
  def show
  end
  

  # GET /apimaps/new
  def new
    @apimap = Apimap.new
  end

  # GET /apimaps/1/edit
  def edit
  end

  # POST /apimaps
  # POST /apimaps.json
  def create
    @apimap = Apimap.new(apimap_params)

    respond_to do |format|
      if @apimap.save
        format.html { redirect_to '/apimaps', notice: 'Apimap was successfully created.' }
        format.json { render :show, status: :created, location: @apimap }
      else
        format.html { render :new }
        format.json { render json: @apimap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apimaps/1
  # PATCH/PUT /apimaps/1.json
  def update
    respond_to do |format|
      if @apimap.update(apimap_params)
        format.html { redirect_to @apimap, notice: 'Apimap was successfully updated.' }
        format.json { render :show, status: :ok, location: @apimap }
      else
        format.html { render :edit }
        format.json { render json: @apimap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apimaps/1
  # DELETE /apimaps/1.json
  def destroy
    @apimap.destroy
    respond_to do |format|
      format.html { redirect_to apimaps_url, notice: 'Apimap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apimap
      @apimap = Apimap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apimap_params
      params.require(:apimap).permit(:name, :latitude, :longitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def map
  end
  
  def test 
  end

  def heatmap
  end
  
end

app/helpers/apimaps_helper.rb
module ApimapsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apimaps/_form.html.erb
<%= form_with(model: apimap, local: true) do |form| %>
  <% if apimap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apimap.errors.count, "error") %> prohibited this apimap from being saved:</h2>

      <ul>
      <% apimap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :apimap_name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :apimap_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :apimap_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apimaps/edit.html.erb
<h1>Editing Apimap</h1>

<%= render 'form', apimap: @apimap %>

<%= link_to 'Show', @apimap %> |
<%= link_to 'Back', apimaps_path %>

app/views/apimaps/index.html.erb
<h1 style="font-size: 30px; text-align: center;">전국 장애인 스포츠 시설</h1>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(7);
    });    
</script>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apimaps.each do |apimap| %>
      <tr>
        <td><%= apimap.name %></td>
        <td><%= apimap.latitude %></td>
        <td><%= apimap.longitude %></td>
        <td><%= link_to 'Show', apimap %></td>
        <td><%= link_to 'Edit', edit_apimap_path(apimap) %></td>
        <td><%= link_to 'Destroy', apimap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apimap', new_apimap_path %>

app/views/apimaps/new.html.erb
<h1>New Apimap</h1>

<%= render 'form', apimap: @apimap %>

<%= link_to 'Back', apimaps_path %>

app/views/apimaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apimap.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @apimap.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apimap.longitude %>
</p>

<%= link_to 'Edit', edit_apimap_path(@apimap) %> |
<%= link_to 'Back', apimaps_path %>

app/views/home/index.html.erb
<div class="container">
  <h1 style="text-align: center; font-family: 'Black Han Sans', sans-serif; font-size: 60px;">장애인 생활 체육, 이대로 괜찮은가요?</h1>


  <%#= image_tag ("banddabi.png"),  style: 'height:250px; width:auto;' %>

  <%= link_to  "반다비 체육센터 2025년까지 150개 신규 건립 [장애인 우선사용]", "http://m.mcst.go.kr/m/s_notice/notice/noticeView.jsp?pTp=P&pTpCD=0302000000&pSeq=16824", class: "link" %><br>

  "일상에서 즐기는 생활밀착형 장애인 체육시설인 ‘반다비 체육센터’를 ’25년까지 150개를 신규로 건립한다. 
  시·군·구 단위로 건립되는 ‘반다비 체육센터’는 장애인이 우선적으로 사용하되, 비장애인도 함께 이용하는 통합시설로 운영될 계획이다. 
  체육관형, 수영장형, 종목별 특화형 등으로 세분화해 건립될 ‘반다비 체육센터’는 단순한 체육시설이 아닌 장애인 커뮤니티 센터 및 복합 문화체육시설로 기능할 것으로 기대된다."


  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">1. 장애인 건강 실태 </h1><br>
  우리나라 장애인은 고령화, 만성질환 증가, 사고 및 재해 등의 이유로 계속 증가(252만명, 인구 5%; 보건복지부 2011)하고 있고, 장애인의 건강에 대한 관심이 높아지고 있다. 

  전국 장애인 등록 인구 : 2,545,637
  (증가 폭을 보여주면 좋을 듯) (3년마다)
  2001 1,134,177
  2004 1,610,994
  2007 2,104,889
  2010 2,517,312
  2013 2,501,112
  2017 2,545,637
  <%= image_tag ("people.png"),  style: 'height:450px; width:auto;' %>

  출처 : 보건복지부, 장애인현황 

  장애인은 장애 유형과 정도 등 장애 특성에 따라 이차장애 및 동반질환 등의 다양한 유형의 건강 상의 문제를 가지고 있다. 장애인은 일차장애로 인한 이차 장애의 발생위험을 가지고 있으며, 노화와 관련된 건강문제에 대한 높은 취약성, 건강을 위협하는 행동의 증가, 폭력 노출 위험, 의도 치 않은 부상 등의 다양한 건강위험요인을 가지고 있다. 국립재활원의 2016년 장애인건강관리사업에서 2014년 국민건강보험공단 건강검진 수검률을 분 석한 결과, 장애인 건강검진 수검률은 65.6%로 전체인구 평균 건강검진 수검률 74.4%에 비해 낮 은 수준이었다. 만성질환인 고혈압과 당뇨의 유병률은 전체인구와 비교했을 때, 장애인의 고혈 압 유병률은 43.6%(전체인구 28.9%), 당뇨 유병률은 19.5%(전체인구 11.1%)로 전체인구의 비해 높게 나타나 장애인이 만성질환에 취약계층임을 알 수 있었다. 


  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">2. 장애인 생활 체육의 의의 </h1><br>

    첫째, 생활체육은 약해진 체력과 건강을 회복시켜 준다. 여러 가지 장애로 인한 운동부족은 기본적인 체력의 저하는 물론 신체적 균형을 잃게 함으로써 상해의 위험이나 질병의 가능성을 높게 한다. 
    특히 장애인의 경우 스 포츠는 단순히 즐기는 그 자체 외에도 장애부위의 기능감퇴를 예방하고 나아가 치료적 효과를 기할 수 있어 정상인보다 더 큰 의미를 가진다고 본다.

    둘째, 생활체육은 신체적, 정서적으로 안정감을 가져주며, 이에 대한 적 응력을 키워 준다. 자유로운 형태 속에서 이루어지는 운동은 체내 에너지 를 발산시켜 줌으로써 정서적 불안, 긴장 피로를 해소시켜 정신적, 정서적 안정을 높여준다. 

    셋째, 생활체육은 사회적 발달을 촉진시킨 동요들과의 스포츠 활동, 단 체행동 통해 자신을 통제하고 다른 사람의 입장을 이해하게 한다. 

    넷째, 생활체육은 장애의 치료 및 재활에 도움이 된다. 장애의 조건을 고려하여 생활체육 활동에 참가함으로써 장애를 치료 개선하고 체력의 증 진을 도와주고 복원 능력을 향상시켜 준다.

  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">3. 장애인 생활 체육 참여율 </h1><br>

    이렇게 중요한데 참여율이 저조 

    장애인생활체육 참여율은 매년 증가추세 로 2008년 6.3%, 2009년 7%에서 2012년 10.6%, 2013년 12.3%, 2014년에는 14.1%로 증가하 였다. => 하지만 그래도 적다는걸 강조

  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">4. 장애인 생활 체육 시설의 부족 </h1><br>
    장애인 체육 시설 현황[부족하다] : 
    55개 있다 => 문화체육관광부 / 보건복지부 / 지자체 관할  -> 다혜님 엑셀 파일

  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">5. 우리가 고려한 조건들 </h1><br>
    1. 공공체육시설 이용 장애인 수 
    2. 생활체육 참여 장애인 수  
    3. 전국체전 종목 특화 1위 지역 
    4. 특수 학교 (아직 X)
    5. 기존 시설

  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">6. 기존 시설을 고려한 예측 및 분석 </h1><br>
  <h1 style="text-align: left; font-family: 'Black Han Sans', sans-serif; font-size: 40px;">7. 기존 시설을 고려하지 않은 예측 및 분석 </h1><br>


</div>

app/views/home/map.html.erb
<div style='width: 800px;'>  
  <div id="map" style='width: 800px; height: 400px;'></div>  
</div>  

<script type="text/javascript">  
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 8
    });
  }
  handler = Gmaps.build('Google');  
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
    markers = handler.addMarkers([  
      {  
        "lat": 37.555130,  
        "lng": 126.936837,
        "picture": {  
          "width":  32,  
          "height": 32  
        },  
        "infowindow": "안녕"  
      }  
    ]);  
    handler.bounds.extendWith(markers);  
    handler.fitMapToBounds();  
  });  
</script>

app/views/home/test.html.erb
<!DOCTYPE html>
  <html>
  <head>
  <title>google map</title>
  <meta charset="utf-8">
  <style>
    html,body,#map-canvas {
            height: 100%;
            margin: 0px;
            padding: 0px
   }
    #panel {
      position: absolute;
      top: 5px;
      left: 50%;
      margin-left: -180px;
      z-index: 5;
      background-color: #fff;
      padding: 5px;
      border: 1px solid #999;
  }
  </style>
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api"></script>
   <script>
   var map;
   function initialize() {
           var mapOptions = {
                   zoom : 7,
                   center : new google.maps.LatLng(37.5651, 126.98955), //서울
                   mapTypeId : google.maps.MapTypeId.ROADMAP
           };
           map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
   }
   google.maps.event.addDomListener(window, 'load', initialize);

  var geocoder;
  function codeAddress(address) {
    geocoder = new google.maps.Geocoder();

  var address = document.getElementById('address').value;
    geocoder.geocode( { 'address': address }, function(results, status) {
           if (status == google.maps.GeocoderStatus.OK) {
                   var lat = results[0]['geometry']['location']['lat']();
                   var lng = results[0]['geometry']['location']['lng']();
                   alert(address+" 의 위도는 " + lat + " 이며, 경도는" + lng + " 입니다.");
                   map.setCenter(results[0].geometry.location);    
                   var marker = new google.maps.Marker({
                        map: map,
                           position: results[0].geometry.location,
                         draggable:false,
                         animation:google.maps.Animation.DROP,
                         title:address
                  });
           } else {
             alert('Geocode was not successful for the following reason: ' + status);
           }
     });
   }

   function geocode() {
    var addressList = new Array( '서울', '대구','광주','부산','포항','강릉','전주','광양','거제','김해','대전','울산','마산','수원','인천','군산','파주');
      for(var j in addressList){
        codeAddress(addressList[j]);
     }
   }
  //  function codeAddress(address) {
  //   geocoder = new google.maps.Geocoder();
  //   geocoder.geocode({ 'address': address}, function (results, status));
  //   }
   
   
   </script>
   </head>



   <body>
    <div id="panel">
      <input id="address" type="textbox" value="Seoul"> 
      <input type="button" value="GO" onclick="codeAddress()"></div>
    <div id="map-canvas"></div>
  </body>
 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parasport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.google.com/maps/api/js?key=AIzaSyClpinnI9JneVxCQuAACpQPA4lYq6_3PRA"></script>
    <script src="https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='https://underscorejs.org/underscore-min.js' type='text/javascript'></script>

  </head>

  <header>
    <div class="navigation">
      <div class="nav">
        <ul>
          <li><%= link_to '장애인 시설 히트맵',  '/home/heatmap', :class => "nav-link" %></li>
          <li><%= link_to '몰라',  '/', :class => "nav-link" %></li>
          <li><%= link_to '몰라',  '/', :class => "nav-link" %></li>
        </ul>
      </div>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>